const { modules, glossary } = window.QAQUEST_DATA;
const $ = (sel, root = document) => root.querySelector(sel);
const $$ = (sel, root = document) => Array.from(root.querySelectorAll(sel));
const app = $('#app');
const state = () => QAStore.get();
const byId = id => modules.find(m => m.id === id) || modules[0];
const allQuestions = () => modules.flatMap(m => m.questions);
const shuffle = arr => [...arr].sort(() => Math.random() - 0.5);
const routes = [['dashboard','Dashboard','🏠'],['modules','Módulos','📚'],['simulados','Simulados','⏱️'],['errors','Revisão de erros','🧩'],['glossary','Glossário','🔤'],['about','Sobre a CTFL','🎓'],['roadmap','Roadmap','🗺️']];

function init(){document.documentElement.dataset.theme=state().theme;document.body.classList.toggle('focus',state().focus);renderNav();bindChrome();route();window.addEventListener('hashchange',route);window.addEventListener('qa:toast',e=>toast(e.detail));if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js').catch(()=>{});}
function renderNav(){ $('#mainNav').innerHTML=routes.map(([id,l,i])=>`<a href="#${id}" data-route="${id}"><span>${i}</span>${l}</a>`).join('')+'<hr>'+modules.map(m=>`<a href="#module/${m.id}" data-route="module/${m.id}"><span>${m.icon}</span>${m.title}</a>`).join(''); }
function bindChrome(){ $('#themeToggle').onclick=()=>{const theme=state().theme==='dark'?'light':'dark';QAStore.set({theme});document.documentElement.dataset.theme=theme;}; $('#focusMode').onclick=()=>{const focus=!state().focus;QAStore.set({focus});document.body.classList.toggle('focus',focus);toast(focus?'Modo foco ativado':'Modo foco desativado');}; $('#menuToggle').onclick=()=>document.body.classList.toggle('nav-open'); $('#globalSearch').addEventListener('input',searchGlobal); document.addEventListener('keydown',e=>{if(e.key==='/'&&document.activeElement.tagName!=='INPUT'&&document.activeElement.tagName!=='TEXTAREA'){e.preventDefault();$('#globalSearch').focus();} if(e.key==='Escape')$('#searchResults').classList.remove('open');});}
function route(){document.body.classList.remove('nav-open');const hash=location.hash.replace('#','')||'dashboard';$$('#mainNav a').forEach(a=>a.classList.toggle('active',hash===a.dataset.route));if(hash.startsWith('module/'))return renderModule(hash.split('/')[1],hash.split('/')[2]||'overview');const map={dashboard:renderDashboard,modules:renderModules,simulados:renderSimulados,errors:renderErrors,glossary:renderGlossary,about:renderAbout,roadmap:renderRoadmap};(map[hash]||renderDashboard)();app.focus();updateGoal();}
function shell(title,subtitle,content){app.innerHTML=`<section class="hero"><p class="eyebrow">QA Foundation Quest</p><h1>${title}</h1><p>${subtitle}</p></section>${content}`;}
function pct(n,d){return d?Math.round(n/d*100):0;} function updateGoal(){const s=state(),p=Math.min(100,pct(s.dailyXp,s.goals.dailyXp));$('#dailyGoalText').textContent=`${s.dailyXp}/${s.goals.dailyXp} XP`;$('#dailyGoalBar').style.width=`${p}%`;}
function moduleProgress(m){const s=state();return pct(m.los.filter(([id])=>s.loStatus[id]==='dominado').length,m.los.length);} function totalProgress(){return pct(modules.reduce((a,m)=>a+moduleProgress(m),0),modules.length*100);} 
function stat(label,value,icon){return`<article class="stat"><span>${icon}</span><small>${label}</small><strong>${value}</strong></article>`;}
function perf(){const s=state(),answers=Object.values(s.answers),acc=pct(answers.filter(Boolean).length,answers.length);return {answered:answers.length,acc,strong:bestModule(true),weak:bestModule(false),strongLo:bestLo(true),weakLo:bestLo(false)};}
function bestModule(best){const s=state();const rows=modules.map(m=>{const qs=m.questions.filter(q=>q.id in s.answers);return {name:m.title,score:pct(qs.filter(q=>s.answers[q.id]).length,qs.length),n:qs.length};}).filter(x=>x.n);return rows.sort((a,b)=>best?b.score-a.score:a.score-b.score)[0]?.name||'Sem dados';}
function bestLo(best){const s=state();const map={};allQuestions().forEach(q=>{if(q.id in s.answers){map[q.lo]=map[q.lo]||[0,0];map[q.lo][1]++;if(s.answers[q.id])map[q.lo][0]++;}});const rows=Object.entries(map).map(([lo,[ok,n]])=>({lo,score:pct(ok,n),n}));return rows.sort((a,b)=>best?b.score-a.score:a.score-b.score)[0]?.lo||'Sem dados';}
function renderDashboard(){const s=state(),p=perf(),last=byId(s.lastModule);shell('Dashboard de estudos CTFL','Acompanhe evolução, pontos fracos, metas diárias, sessões de foco e próximos passos.',`<section class="stats-grid">${stat('Progresso geral',totalProgress()+'%','🎯')}${stat('Taxa de acerto',p.acc+'%','✅')}${stat('XP total',s.xp,'⚡')}${stat('Streak',s.streak+' dias','🔥')}</section><section class="panel accent"><div><h2>Continuar estudando</h2><p>Último módulo: <strong>${last.title}</strong>. Próxima sugestão: revisar <strong>${p.weakLo}</strong> e responder 10 questões.</p><div class="progress big"><span style="width:${moduleProgress(last)}%"></span></div></div><a class="btn primary" href="#module/${last.id}">Continuar</a></section><section class="grid two"><div class="panel"><h2>Estatísticas</h2><ul class="clean"><li>Questões respondidas: <strong>${p.answered}</strong></li><li>Módulo mais forte: <strong>${p.strong}</strong></li><li>Módulo mais fraco: <strong>${p.weak}</strong></li><li>LO mais forte: <strong>${p.strongLo}</strong></li><li>LO mais fraco: <strong>${p.weakLo}</strong></li></ul></div><div class="panel"><h2>Evolução</h2><div class="chart"><span style="height:${Math.min(100,s.xp/4)}%">XP</span><span style="height:${Math.min(100,s.examHistory.length*15)}%">Sim</span><span style="height:${p.acc||5}%">Acerto</span></div></div></section><section class="quick-actions"><button class="btn" onclick="startStudyTimer(25)">🍅 Pomodoro 25</button><button class="btn" onclick="startStudyTimer(50)">⏳ Foco 50</button><button class="btn" onclick="setDailyGoal(10)">Meta 10 questões</button><a href="#simulados">Simulados</a></section>`);}
function setDailyGoal(n){QAStore.set({goals:{...state().goals,dailyQuestions:n}});toast(`Meta diária definida: ${n} questões`);} function startStudyTimer(min){let end=Date.now()+min*60000;toast(`Sessão de ${min} min iniciada`);clearInterval(window.studyTimer);window.studyTimer=setInterval(()=>{if(Date.now()>=end){clearInterval(window.studyTimer);QAStore.addXp(10,'sessão de estudo concluída');}},1000);}
function renderModules(){shell('Módulos oficiais CTFL v4.0.1','Conteúdo profundo, LOs enriquecidos, flashcards, questões e exercícios em abas internas.',`<section class="module-grid">${modules.map(m=>`<article class="module-card"><div class="module-icon">${m.icon}</div><h2>${m.title}</h2><p>${m.intro}</p><p><span class="pill">${m.topics.length} tópicos</span><span class="pill">${m.cards.length} flashcards</span><span class="pill">${m.questions.length} questões</span></p><div class="progress"><span style="width:${moduleProgress(m)}%"></span></div><a class="btn primary" href="#module/${m.id}">Estudar</a></article>`).join('')}</section>`);}
function renderModule(id,tab='overview'){const m=byId(id);QAStore.set({lastModule:m.id});const tabs=[['overview','Visão Geral'],['lesson','Aula'],['los','Learning Objectives'],['cards','Flashcards'],['questions','Questões'],['exercises','Exercícios'],['review','Revisão']];shell(`${m.icon} ${m.title}`,m.intro,`<nav class="tabs">${tabs.map(([k,l])=>`<a class="${tab===k?'active':''}" href="#module/${m.id}/${k}">${l}</a>`).join('')}</nav><section>${moduleTab(m,tab)}</section>`);}
function moduleTab(m,tab){if(tab==='lesson')return `<div class="accordion">${m.topics.map(t=>`<details open><summary>${t.title}</summary><h3>Conceito</h3><p>${t.concept}</p><h3>Explicação simplificada</h3><p>${t.simple}</p><h3>Exemplo real</h3><p>${t.example}</p><h3>Como aparece na CTFL</h3><p>${t.exam}</p><h3>Erros comuns</h3><p>${t.errors}</p><h3>Dica de memorização</h3><p>${t.memory}</p></details>`).join('')}</div>`;if(tab==='los')return `<div class="lo-list">${m.los.map(([id,k,txt])=>`<article><div><strong>${id}</strong> <span class="pill">${k}</span><p>${txt}</p><p>Importância: orienta estudo, cobertura e seleção de questões. Tópicos relacionados: ${m.topics.filter(t=>t.related.includes(id)).map(t=>t.title).slice(0,4).join(', ')||m.topics[0].title}. Questões associadas: ${m.questions.filter(q=>q.lo===id).length}.</p></div><button class="btn small" onclick="markLo('${id}')">Marcar dominado</button></article>`).join('')}</div>`;if(tab==='cards')return renderCards(m);if(tab==='questions')return renderQuestionBank(m);if(tab==='exercises')return `<div class="exercise-list">${m.exercises.map(e=>`<article><p>${e}</p><textarea placeholder="Escreva sua resposta discursiva..."></textarea></article>`).join('')}</div>`;if(tab==='review')return `<section class="panel"><h2>Resumo rápido</h2><p>${m.summary}</p><ul>${m.topics.slice(0,8).map(t=>`<li><strong>${t.title}:</strong> ${t.simple}</li>`).join('')}</ul></section>`;return `<section class="grid two"><div class="panel"><h2>Como cai na prova</h2><p>${m.exam}</p><h2>Aplicação prática</h2><p>${m.practice}</p><p><span class="pill">Dificuldade: ${m.difficulty}</span><span class="pill">${m.weight}</span></p></div><div class="panel"><h2>Estatísticas pessoais</h2><ul class="clean"><li>Progresso em LOs: <strong>${moduleProgress(m)}%</strong></li><li>Flashcards concluídos: <strong>${Object.keys(state().cardStatus||{}).filter(k=>k.startsWith(m.id)&&state().cardStatus[k]==='done').length}</strong></li><li>Questões respondidas: <strong>${m.questions.filter(q=>q.id in state().answers).length}/${m.questions.length}</strong></li></ul></div></section>`;}
function markLo(id){QAStore.set({loStatus:{...state().loStatus,[id]:'dominado'}});QAStore.addXp(5,'LO dominado');route();}
function renderCards(m){const s=state();return `<div class="cards">${m.cards.map(c=>`<article class="flash-shell"><button class="flashcard" onclick="this.classList.toggle('flipped')"><span class="front"><strong>${c.term}</strong><em>${c.front}</em></span><span class="back"><strong>Resposta</strong><em>${c.back}</em><small>${c.example}</small></span></button><div class="card-actions"><button onclick="setCard('${c.id}','favorite')">⭐</button><button onclick="setCard('${c.id}','pending')">Pendente</button><button onclick="setCard('${c.id}','hard')">Difícil</button><button onclick="setCard('${c.id}','done')">Concluído</button><span class="pill">${s.cardStatus?.[c.id]||'novo'}</span></div></article>`).join('')}</div>`;}
function setCard(id,status){QAStore.set({cardStatus:{...(state().cardStatus||{}),[id]:status}});if(status==='done')QAStore.addXp(2,'flashcard concluído');route();}
function renderQuestionBank(m){return `<div class="filters"><select id="qFilter" onchange="filterQuestions('${m.id}')"><option value="">Todas</option><option>fácil</option><option>médio</option><option>difícil</option></select></div><div id="questionList">${m.questions.map(q=>questionRow(q)).join('')}</div>`;}
function questionRow(q){return `<article class="question-row" data-dif="${q.difficulty}"><div class="quiz-head"><strong>${q.lo}</strong><span class="pill ${q.difficulty}">${q.difficulty}</span></div><p>${q.text}</p><div class="options">${q.options.map((o,i)=>`<button onclick="answerQuestion('${q.id}',${i})">${String.fromCharCode(65+i)}. ${o}</button>`).join('')}</div><div id="fb-${q.id}"></div></article>`;}
function filterQuestions(id){const v=$('#qFilter').value;$$('#questionList .question-row').forEach(r=>r.style.display=!v||r.dataset.dif===v?'':'none');}
function answerQuestion(qid,i){const q=allQuestions().find(x=>x.id===qid),ok=i===q.answer;QAStore.set({answers:{...state().answers,[qid]:ok},wrongQuestions:ok?state().wrongQuestions.filter(x=>x!==qid):[...new Set([...state().wrongQuestions,qid])]});QAStore.addXp(ok?3:1,ok?'questão correta':'questão revisada');$(`#fb-${qid}`).innerHTML=`<div class="feedback ${ok?'ok':'bad'}"><strong>${ok?'Correto':'Revise'}</strong><p>${q.explanation}</p><ol>${q.optionExplanations.map(x=>`<li>${x}</li>`).join('')}</ol></div>`;}
function renderSimulados(){shell('Simulados inteligentes','Pratique com sorteio sem repetição, navegação lateral, marcação para revisão e relatório detalhado.',`<section class="sim-grid"><button class="sim" onclick="startExam('quick')">⚡ Simulado rápido<br><small>10 aleatórias</small></button>${modules.map(m=>`<button class="sim" onclick="startExam('module','${m.id}')">${m.icon} ${m.title}<br><small>Por módulo</small></button>`).join('')}<button class="sim" onclick="startExam('full')">🎓 Simulado completo<br><small>40 questões sem repetição</small></button></section>`);}
function startExam(type,id){const pool=type==='module'?byId(id).questions:allQuestions(),size=type==='quick'?10:type==='full'?40:Math.min(20,pool.length);window.currentExam={type,items:shuffle(pool).slice(0,size),answers:{},marked:{},idx:0};renderExam();}
function renderExam(){const ex=window.currentExam,q=ex.items[ex.idx];app.innerHTML=`<section class="exam"><aside class="exam-nav">${ex.items.map((_,i)=>`<button class="${i===ex.idx?'active':''} ${ex.answers[i]!==undefined?'done':''}" onclick="currentExam.idx=${i};renderExam()">${i+1}</button>`).join('')}<button class="btn primary" onclick="finishExam()">Finalizar</button></aside><article class="panel"><div class="quiz-head"><h2>Questão ${ex.idx+1}/${ex.items.length}</h2><button class="btn" onclick="currentExam.marked[currentExam.idx]=!currentExam.marked[currentExam.idx];renderExam()">${ex.marked[ex.idx]?'★ Revisar':'☆ Marcar'}</button></div>${questionRow(q)}<div class="accent"><button class="btn" onclick="currentExam.idx=Math.max(0,currentExam.idx-1);renderExam()">Anterior</button><button class="btn" onclick="currentExam.idx=Math.min(currentExam.items.length-1,currentExam.idx+1);renderExam()">Próxima</button></div></article></section>`;}
function finishExam(){const ex=window.currentExam;let ok=0;ex.items.forEach((q,i)=>{if(ex.answers[i]===q.answer)ok++;});QAStore.set({examHistory:[...state().examHistory,{date:QAStore.today(),score:pct(ok,ex.items.length),total:ex.items.length}]});QAStore.addXp(ok,'simulado finalizado');shell('Resultado do simulado',`Você acertou ${ok}/${ex.items.length} (${pct(ok,ex.items.length)}%).`,`<section class="panel"><h2>Relatório detalhado</h2>${ex.items.map((q,i)=>`<p><strong>${i+1}. ${q.lo}</strong> — ${ex.answers[i]===q.answer?'✅':'❌'} ${q.explanation}</p>`).join('')}</section>`);}
function renderErrors(){const qs=state().wrongQuestions.map(id=>allQuestions().find(q=>q.id===id)).filter(Boolean);shell('Revisão de erros','Transforme erros em retenção com explicação detalhada e alternativas incorretas.',qs.length?qs.map(questionRow).join(''):'<section class="panel"><p>Nenhum erro pendente. Faça simulados para alimentar esta fila.</p></section>');}
function renderGlossary(){shell('Glossário CTFL expandido','Mais de 100 termos com busca instantânea, favoritos, categoria e termos relacionados.',`<div class="filters"><input id="glossFilter" oninput="filterGlossary()" placeholder="Pesquisar termo..."><select id="catFilter" onchange="filterGlossary()"><option value="">Todas categorias</option>${[...new Set(glossary.map(g=>g.category))].map(c=>`<option>${c}</option>`).join('')}</select></div><section class="glossary-list" id="glossList">${glossary.map(termCard).join('')}</section>`);}
function termCard(t){return`<article data-term="${t.name.toLowerCase()} ${t.category.toLowerCase()}"><button class="fav" onclick="favTerm('${t.name}')">${state().favoriteTerms.includes(t.name)?'★':'☆'}</button><h2>${t.name}</h2><span class="pill">${t.category}</span><p>${t.definition}</p><p><strong>Simples:</strong> ${t.simple}</p><p><strong>Exemplo:</strong> ${t.example}</p><p><strong>Relacionados:</strong> ${t.related.join(', ')}</p></article>`;}
function filterGlossary(){const q=$('#glossFilter').value.toLowerCase(),c=$('#catFilter').value.toLowerCase();$$('#glossList article').forEach(a=>a.style.display=a.dataset.term.includes(q)&&a.dataset.term.includes(c)?'':'none');}
function favTerm(name){const f=state().favoriteTerms;QAStore.set({favoriteTerms:f.includes(name)?f.filter(x=>x!==name):[...f,name]});renderGlossary();}
function renderAbout(){shell('Sobre a CTFL v4.0.1','Estrutura da certificação, carreira, plano de 30 dias e estratégia de prova.',`<section class="grid two">${['Estrutura da certificação: 40 questões, múltipla escolha, foco em K1-K3 e pontuação mínima definida pelo exame.','Histórico do ISTQB: programa internacional com vocabulário comum para profissionais de teste.','Carreira: base para QA, automação, qualidade ágil, análise de testes e liderança técnica.','Trilha: Foundation, Agile, Specialist e Advanced conforme objetivos profissionais.','Como estudar: combine aula, flashcards, questões por LO e simulados completos cronometrados.','Plano de 30 dias: fundamentos, ciclo, estático, técnicas, gerenciamento, ferramentas, revisão e simulados.','Estratégia de prova: marque dúvidas, elimine absolutismos, desenhe cenários K3 e controle tempo.','Pegadinhas comuns: confundir reteste/regressão, severidade/prioridade e erro/defeito/falha.'].map(x=>`<article class="panel"><p>${x}</p></article>`).join('')}</section>`);}
function renderRoadmap(){const plan=d=>Array.from({length:d},(_,i)=>`Dia ${i+1}: ${modules[i%modules.length].title} + ${i%3===2?'simulado e revisão de erros':'aula, flashcards e 10 questões'}`);shell('Roadmap real de preparação','Planos de 15, 30 e 60 dias com metas, módulos, simulados e checkpoints.',`<section class="grid two">${[15,30,60].map(d=>`<article class="panel"><h2>Plano ${d} dias</h2><p>Meta: estudar todos os módulos, revisar LOs fracos e concluir simulados progressivos.</p><details><summary>Ver agenda</summary><ol>${plan(d).map(x=>`<li>${x}</li>`).join('')}</ol></details><p><strong>Checkpoints:</strong> 50%, 70% e 85% de acerto antes da prova.</p></article>`).join('')}</section>`);}
function searchGlobal(e){const q=e.target.value.toLowerCase(),box=$('#searchResults');if(q.length<2){box.classList.remove('open');return;}const items=[...modules.map(m=>({t:m.title,s:m.intro,u:`#module/${m.id}`})),...glossary.map(g=>({t:g.name,s:g.definition,u:'#glossary'})),...allQuestions().slice(0,80).map(x=>({t:x.lo,s:x.text,u:`#module/${x.module}/questions`}))].filter(x=>(x.t+x.s).toLowerCase().includes(q)).slice(0,8);box.innerHTML=items.map(i=>`<a href="${i.u}"><strong>${i.t}</strong><small>${i.s}</small></a>`).join('');box.classList.add('open');}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2600);} 
const realAnswer = answerQuestion; window.answerQuestion = (qid,i)=>{ if(window.currentExam){const idx=window.currentExam.idx; window.currentExam.answers[idx]=i;} realAnswer(qid,i); };
window.filterQuestions=filterQuestions;window.markLo=markLo;window.setCard=setCard;window.startExam=startExam;window.renderExam=renderExam;window.finishExam=finishExam;window.filterGlossary=filterGlossary;window.favTerm=favTerm;window.startStudyTimer=startStudyTimer;window.setDailyGoal=setDailyGoal;
init();
